spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curry
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx@xxx.com
    password: xxx
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
